### ISSUE TITLE
Support for ansible vault

### ISSUE THREAD

**Issue by ramondelafuente** [saubermacherag/ansible-playbook-docker-action#1]
Feature request: 

It would be nice to have support for vault files in this action. It's a bit of an experimental landscape for github actions still, but it seems like this is a viable solution:

https://misfra.me/2019/10/using-ansible-with-github-actions/

Basically, the entrypoint script needs to read a variable and write it to a file (see https://github.com/Preetam/transverse/blob/master/.github/actions/ansible/entrypoint.sh).

**Comment by ppoetz** [comment]
Thanks for this great idea. This will solve our issue with having multiline secrets stored in Github secrets too. Our problem is that multiline secrets such as ssh keys will get saved with spaces instead of newlines in Github secrets. 
With this vaulting approach we can work around this issue.
I'll implement this request

**Comment by ramondelafuente** [comment]
Yeah, I was running into that problem as well (that my private key is not being accepted), but I've seen multiple examples of actions that just write out the private key to a file and I assume that that works for those workflows. Some use `ssh-add` on the key file so that might be a way to go...

I don't really understand what the spaces have to do with it though. As I understand the documentation only the variable _names_ can't have spaces, not the _values_. But the keys are obfuscated in the output so it's hard to determine what's actually written to the file.

**Comment by ppoetz** [comment]
@ramondelafuente 
Version v1.2 should suffice now.
https://github.com/saubermacherag/ansible-playbook-docker-action/releases/tag/v1.2

**Comment by ppoetz** [comment]
Closing this one. Works out now with version 1.2.
If you have any further suggestions please let us know in a new issue or PR.
Thanks for your contribution :-D

**Comment by ramondelafuente** [comment]
👍
