### ISSUE TITLE
k8s module not working

### ISSUE THREAD

**Issue by nebbie-corp** [saubermacherag/ansible-playbook-docker-action#6]
When running ansible with k8s module I get the following error:

TASK [Create a namespace] *********************************************
task path: /github/workspace/install-dev.yaml:7
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named kubernetes
 [WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/local/bin/python2.7, but future installation of another
Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/
reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/local/bin/python2.7"}, "changed": false, "error": "No module named kubernetes", "msg": "Failed to import the required Python library (openshift) on 655f48aa0af3's Python /usr/local/bin/python2.7. Please read module documentation and install in the appropriate location"}

**Comment by ppoetz** [comment]
hey @nebbie-corp 
Could you post some more context? Eg the playbook itself would be helpful to reproduce this issue.

**Comment by nebbie-corp** [comment]
Hey @ppoetz,

I solved this problem by adding the openshift module in the base image.

https://github.com/nebbie-corp/docker-ansible-alpine/blob/master/Dockerfile#L33
